rules:
  indent:
    - 2
    - 4
    - SwitchCase: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
env:
  es6: true
  browser: true
  node: true
  mocha: true
ecmaFeatures:
  modules: true
  forOf: false
extends: 'eslint:recommended'
