/*
 * Extracts the golden fixture `moment-2026a-golden.json` from moment-timezone unpacked data.
 * The data is not regenerated by tests; rerun only when the fixture zones change:
 *
 *   node test/fixtures/extractGolden.js <moment-timezone>/data/unpacked/2026a.json > test/fixtures/moment-2026a-golden.json
 */

import fs from 'node:fs';

export const GOLDEN_ZONES = [
    'Africa/Casablanca', 'America/New_York', 'America/Nuuk', 'America/Santiago', 'Asia/Gaza',
    'Asia/Jerusalem', 'Australia/Lord_Howe', 'Australia/Sydney', 'Europe/Dublin', 'Pacific/Chatham',
];

// the first years after zic's explicit transitions, and the last years of the data
export const GOLDEN_WINDOWS = [[2030, 2050], [2480, 2499]];

/**
 * @return {{abbrs: string[], untils: (number|null)[], offsets: number[]}} the periods that overlap
 *  the years `from` to `to`
 */
export function sliceYears(zone, from, to) {
    const firstIndex = (time) => zone.untils.findIndex((until) => until == null || until >= time);
    const start = firstIndex(Date.UTC(from, 0, 1));
    const end = firstIndex(Date.UTC(to + 1, 0, 1)) + 1;
    return {
        abbrs: zone.abbrs.slice(start, end),
        untils: zone.untils.slice(start, end),
        offsets: zone.offsets.slice(start, end),
    };
}

function main(file) {
    const zones = new Map(JSON.parse(fs.readFileSync(file, 'utf8')).zones.map((zone) => [zone.name, zone]));
    const golden = {};
    for (const name of GOLDEN_ZONES) {
        golden[name] = GOLDEN_WINDOWS.map(([from, to]) => ({ from, to, ...sliceYears(zones.get(name), from, to) }));
    }
    process.stdout.write(`${JSON.stringify(golden)}\n`);
}

if (process.argv[1] && process.argv[1].endsWith('extractGolden.js') && process.argv[2]) {
    main(process.argv[2]);
}
