/*
 * @copyright (c) 2026-present, Philipp Thürwächter, Pattrick Hüper
 * @license BSD-3-Clause (see LICENSE in the root directory of this source tree)
 */

import { expect } from 'chai';

import { Instant, LocalDateTime } from '@js-joda/core';

import { MomentZoneRules } from '../src/MomentZoneRules';

/**
 * Data generated by @js-joda/tzdb-builder keeps a separate period whenever the isdst flag changes,
 * even when offset and abbreviation stay the same. Such a transition must behave exactly like
 * no transition at all.
 *
 * America/Argentina/Buenos_Aires (tzdb 2026a): from 1999-10-03 to 2000-03-03 the zone stays at -03,
 * but is daylight saving time (standard time was -04). Then -03 until the real change to -02 on 2007-12-30.
 */
describe('MomentZoneRules with isdst-only transitions', () => {
    const split = new MomentZoneRules({
        name: 'split',
        untils: [938919600000, 952052400000, 1198983600000, Infinity],
        offsets: [180, 180, 180, 120],
    });
    // the same periods merged on offset (as in moment-timezone data)
    const merged = new MomentZoneRules({
        name: 'merged',
        untils: [1198983600000, Infinity],
        offsets: [180, 120],
    });

    const forEachLocalDateTime = (from, to, callback) => {
        for (let ldt = from; ldt.isBefore(to); ldt = ldt.plusMinutes(30)) {
            callback(ldt);
        }
    };
    const asString = (value) => (value == null ? null : value.toString());

    it('resolves local date-times around the isdst-only transitions like merged data', () => {
        const ranges = [
            [LocalDateTime.parse('1999-10-02T00:00'), LocalDateTime.parse('1999-10-04T00:00')],
            [LocalDateTime.parse('2000-03-02T00:00'), LocalDateTime.parse('2000-03-04T00:00')],
        ];
        for (const [from, to] of ranges) {
            forEachLocalDateTime(from, to, (ldt) => {
                expect(split.offsetOfLocalDateTime(ldt).toString(), ldt.toString()).to.equal(merged.offsetOfLocalDateTime(ldt).toString());
                expect(split.validOffsets(ldt).map(asString), ldt.toString()).to.eql(merged.validOffsets(ldt).map(asString));
                expect(split.transition(ldt), ldt.toString()).to.equal(null);
                expect(split.isValidOffset(ldt, split.offsetOfLocalDateTime(ldt)), ldt.toString()).to.equal(true);
            });
        }
    });

    it('resolves the exact local date-time of an isdst-only transition as a normal offset', () => {
        // 1999-10-03T03:00Z is 1999-10-03T00:00 at -03
        const ldt = LocalDateTime.parse('1999-10-03T00:00');
        expect(split.validOffsets(ldt).map(asString)).to.eql(['-03:00']);
        expect(split.transition(ldt)).to.equal(null);
    });

    it('resolves instants around the isdst-only transitions like merged data', () => {
        for (const epochMilli of [938919600000, 952052400000]) {
            for (const delta of [-3600000, -1, 0, 1, 3600000]) {
                const instant = Instant.ofEpochMilli(epochMilli + delta);
                expect(split.offsetOfInstant(instant).toString()).to.equal(merged.offsetOfInstant(instant).toString());
            }
        }
    });

    it('still detects the following real transition (gap on 2007-12-30)', () => {
        // 2007-12-30T03:00Z: clocks jump from 00:00 (-03) to 01:00 (-02)
        const ldt = LocalDateTime.parse('2007-12-30T00:30');
        expect(split.validOffsets(ldt)).to.eql([]);
        expect(asString(split.transition(ldt))).to.equal(asString(merged.transition(ldt)));
        expect(split.transition(ldt).isGap()).to.equal(true);
    });
});
