name: Saucelabs Browser Tests

on:
  push:
    branches:
      - master
      - test-push

jobs:
#  sauce:
#    name: Saucelabs Tests (non forked only)
#    runs-on: ubuntu-latest
#    if: github.event.push || github.event.pull_request.head.repo.full_name == github.repository
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup node 14
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - name: Setup sauce connect
#        uses: saucelabs/sauce-connect-action@v1
#        with:
#          username: ${{ secrets.SAUCE_USERNAME }}
#          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
#          tunnelIdentifier: github-action-tunnel
#          scVersion: 4.6.4
#      - name: Install and bootstrap
#        run: |
#          npm install;
#          npx lerna clean -y;
#          npx lerna link;
#          npx lerna bootstrap --no-ci;
#      - name: karma tests with sauce
#        env:
#          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
#          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
#        run: |
#          set -e;
#          npx lerna run --stream test-saucelabs;
  dump-env:
    name: Dump environment and context
    runs-on: ubuntu-latest
    if: ${{ github.event.push }}
    steps:
      - name: dump github context
        env:
          GITUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITUB_CONTEXT"
      - name: dump default env
        run: export
